
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: YangLei
gitment_repo: https://github.com/yarnA/hexo-theme-vexo
gitment_oauth_id:
gitment_oauth_secret:

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:
google_analytics:
# disqus config
disqus_shortname:

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: https://tva4.sinaimg.cn/crop.0.0.996.996.180/005PTvyjjw8ezt4ov75s4j30ro0ro40y.jpg?KID=imgbed,tva&Expires=1587268600&ssig=bLQd%2BrP5U6
  description: "I love x y."
  weibo_username: p/1005055347486627/home?from=page_100505_profile&wvr=6&mod=data&is_all=1#place
  twitter_username: YangLei
  github_username:  yarnA
  zhihu_username: YangLei
  douban_username: YangLei
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
